package matthiasseifert.de.sakuranimangacollection.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BOOK".
 */
public class Book {

    private Long id;
    private String Isbn;
    private String Title;
    private Integer Year;
    private String Language;
    private String publisher;
    private String Edition;
    private Boolean IsEbook;
    private String CoverImage;
    private Double Value;

    public Book() {
    }

    public Book(Long id) {
        this.id = id;
    }

    public Book(Long id, String Isbn, String Title, Integer Year, String Language, String publisher, String Edition, Boolean IsEbook, String CoverImage, Double Value) {
        this.id = id;
        this.Isbn = Isbn;
        this.Title = Title;
        this.Year = Year;
        this.Language = Language;
        this.publisher = publisher;
        this.Edition = Edition;
        this.IsEbook = IsEbook;
        this.CoverImage = CoverImage;
        this.Value = Value;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIsbn() {
        return Isbn;
    }

    public void setIsbn(String Isbn) {
        this.Isbn = Isbn;
    }

    public String getTitle() {
        return Title;
    }

    public void setTitle(String Title) {
        this.Title = Title;
    }

    public Integer getYear() {
        return Year;
    }

    public void setYear(Integer Year) {
        this.Year = Year;
    }

    public String getLanguage() {
        return Language;
    }

    public void setLanguage(String Language) {
        this.Language = Language;
    }

    public String getPublisher() {
        return publisher;
    }

    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    public String getEdition() {
        return Edition;
    }

    public void setEdition(String Edition) {
        this.Edition = Edition;
    }

    public Boolean getIsEbook() {
        return IsEbook;
    }

    public void setIsEbook(Boolean IsEbook) {
        this.IsEbook = IsEbook;
    }

    public String getCoverImage() {
        return CoverImage;
    }

    public void setCoverImage(String CoverImage) {
        this.CoverImage = CoverImage;
    }

    public Double getValue() {
        return Value;
    }

    public void setValue(Double Value) {
        this.Value = Value;
    }

}
