package matthiasseifert.de.sakuranimangacollection.model;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import matthiasseifert.de.sakuranimangacollection.model.BookDao;
import matthiasseifert.de.sakuranimangacollection.model.SeriesDao;
import matthiasseifert.de.sakuranimangacollection.model.SeriesAssignmentDao;
import matthiasseifert.de.sakuranimangacollection.model.PersonDao;
import matthiasseifert.de.sakuranimangacollection.model.PersonAssignmentDao;
import matthiasseifert.de.sakuranimangacollection.model.RolesDao;
import matthiasseifert.de.sakuranimangacollection.model.PersonRolesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        BookDao.createTable(db, ifNotExists);
        SeriesDao.createTable(db, ifNotExists);
        SeriesAssignmentDao.createTable(db, ifNotExists);
        PersonDao.createTable(db, ifNotExists);
        PersonAssignmentDao.createTable(db, ifNotExists);
        RolesDao.createTable(db, ifNotExists);
        PersonRolesDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        BookDao.dropTable(db, ifExists);
        SeriesDao.dropTable(db, ifExists);
        SeriesAssignmentDao.dropTable(db, ifExists);
        PersonDao.dropTable(db, ifExists);
        PersonAssignmentDao.dropTable(db, ifExists);
        RolesDao.dropTable(db, ifExists);
        PersonRolesDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(BookDao.class);
        registerDaoClass(SeriesDao.class);
        registerDaoClass(SeriesAssignmentDao.class);
        registerDaoClass(PersonDao.class);
        registerDaoClass(PersonAssignmentDao.class);
        registerDaoClass(RolesDao.class);
        registerDaoClass(PersonRolesDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
