package matthiasseifert.de.sakuranimangacollection.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import matthiasseifert.de.sakuranimangacollection.model.Book;
import matthiasseifert.de.sakuranimangacollection.model.Series;
import matthiasseifert.de.sakuranimangacollection.model.SeriesAssignment;
import matthiasseifert.de.sakuranimangacollection.model.Person;
import matthiasseifert.de.sakuranimangacollection.model.PersonAssignment;
import matthiasseifert.de.sakuranimangacollection.model.Roles;
import matthiasseifert.de.sakuranimangacollection.model.PersonRoles;

import matthiasseifert.de.sakuranimangacollection.model.BookDao;
import matthiasseifert.de.sakuranimangacollection.model.SeriesDao;
import matthiasseifert.de.sakuranimangacollection.model.SeriesAssignmentDao;
import matthiasseifert.de.sakuranimangacollection.model.PersonDao;
import matthiasseifert.de.sakuranimangacollection.model.PersonAssignmentDao;
import matthiasseifert.de.sakuranimangacollection.model.RolesDao;
import matthiasseifert.de.sakuranimangacollection.model.PersonRolesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookDaoConfig;
    private final DaoConfig seriesDaoConfig;
    private final DaoConfig seriesAssignmentDaoConfig;
    private final DaoConfig personDaoConfig;
    private final DaoConfig personAssignmentDaoConfig;
    private final DaoConfig rolesDaoConfig;
    private final DaoConfig personRolesDaoConfig;

    private final BookDao bookDao;
    private final SeriesDao seriesDao;
    private final SeriesAssignmentDao seriesAssignmentDao;
    private final PersonDao personDao;
    private final PersonAssignmentDao personAssignmentDao;
    private final RolesDao rolesDao;
    private final PersonRolesDao personRolesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookDaoConfig = daoConfigMap.get(BookDao.class).clone();
        bookDaoConfig.initIdentityScope(type);

        seriesDaoConfig = daoConfigMap.get(SeriesDao.class).clone();
        seriesDaoConfig.initIdentityScope(type);

        seriesAssignmentDaoConfig = daoConfigMap.get(SeriesAssignmentDao.class).clone();
        seriesAssignmentDaoConfig.initIdentityScope(type);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        personAssignmentDaoConfig = daoConfigMap.get(PersonAssignmentDao.class).clone();
        personAssignmentDaoConfig.initIdentityScope(type);

        rolesDaoConfig = daoConfigMap.get(RolesDao.class).clone();
        rolesDaoConfig.initIdentityScope(type);

        personRolesDaoConfig = daoConfigMap.get(PersonRolesDao.class).clone();
        personRolesDaoConfig.initIdentityScope(type);

        bookDao = new BookDao(bookDaoConfig, this);
        seriesDao = new SeriesDao(seriesDaoConfig, this);
        seriesAssignmentDao = new SeriesAssignmentDao(seriesAssignmentDaoConfig, this);
        personDao = new PersonDao(personDaoConfig, this);
        personAssignmentDao = new PersonAssignmentDao(personAssignmentDaoConfig, this);
        rolesDao = new RolesDao(rolesDaoConfig, this);
        personRolesDao = new PersonRolesDao(personRolesDaoConfig, this);

        registerDao(Book.class, bookDao);
        registerDao(Series.class, seriesDao);
        registerDao(SeriesAssignment.class, seriesAssignmentDao);
        registerDao(Person.class, personDao);
        registerDao(PersonAssignment.class, personAssignmentDao);
        registerDao(Roles.class, rolesDao);
        registerDao(PersonRoles.class, personRolesDao);
    }
    
    public void clear() {
        bookDaoConfig.getIdentityScope().clear();
        seriesDaoConfig.getIdentityScope().clear();
        seriesAssignmentDaoConfig.getIdentityScope().clear();
        personDaoConfig.getIdentityScope().clear();
        personAssignmentDaoConfig.getIdentityScope().clear();
        rolesDaoConfig.getIdentityScope().clear();
        personRolesDaoConfig.getIdentityScope().clear();
    }

    public BookDao getBookDao() {
        return bookDao;
    }

    public SeriesDao getSeriesDao() {
        return seriesDao;
    }

    public SeriesAssignmentDao getSeriesAssignmentDao() {
        return seriesAssignmentDao;
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public PersonAssignmentDao getPersonAssignmentDao() {
        return personAssignmentDao;
    }

    public RolesDao getRolesDao() {
        return rolesDao;
    }

    public PersonRolesDao getPersonRolesDao() {
        return personRolesDao;
    }

}
