package matthiasseifert.de.sakuranimangacollection.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import matthiasseifert.de.sakuranimangacollection.model.PersonAssignment;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PERSON_ASSIGNMENT".
*/
public class PersonAssignmentDao extends AbstractDao<PersonAssignment, Void> {

    public static final String TABLENAME = "PERSON_ASSIGNMENT";

    /**
     * Properties of entity PersonAssignment.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property PersonId = new Property(0, Long.class, "PersonId", false, "PERSON_ID");
        public final static Property BookId = new Property(1, Long.class, "BookId", false, "BOOK_ID");
    };


    public PersonAssignmentDao(DaoConfig config) {
        super(config);
    }
    
    public PersonAssignmentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PERSON_ASSIGNMENT\" (" + //
                "\"PERSON_ID\" INTEGER," + // 0: PersonId
                "\"BOOK_ID\" INTEGER);"); // 1: BookId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PERSON_ASSIGNMENT\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PersonAssignment entity) {
        stmt.clearBindings();
 
        Long PersonId = entity.getPersonId();
        if (PersonId != null) {
            stmt.bindLong(1, PersonId);
        }
 
        Long BookId = entity.getBookId();
        if (BookId != null) {
            stmt.bindLong(2, BookId);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public PersonAssignment readEntity(Cursor cursor, int offset) {
        PersonAssignment entity = new PersonAssignment( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // PersonId
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1) // BookId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PersonAssignment entity, int offset) {
        entity.setPersonId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBookId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(PersonAssignment entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(PersonAssignment entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
