package matthiasseifert.de.sakuranimangacollection.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PERSON_ROLES".
 */
public class PersonRoles {

    private Long PersonId;
    private Long RoleId;

    public PersonRoles() {
    }

    public PersonRoles(Long PersonId, Long RoleId) {
        this.PersonId = PersonId;
        this.RoleId = RoleId;
    }

    public Long getPersonId() {
        return PersonId;
    }

    public void setPersonId(Long PersonId) {
        this.PersonId = PersonId;
    }

    public Long getRoleId() {
        return RoleId;
    }

    public void setRoleId(Long RoleId) {
        this.RoleId = RoleId;
    }

}
