package matthiasseifert.de.sakuranimangacollection.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PERSON_ASSIGNMENT".
 */
public class PersonAssignment {

    private Long PersonId;
    private Long BookId;

    public PersonAssignment() {
    }

    public PersonAssignment(Long PersonId, Long BookId) {
        this.PersonId = PersonId;
        this.BookId = BookId;
    }

    public Long getPersonId() {
        return PersonId;
    }

    public void setPersonId(Long PersonId) {
        this.PersonId = PersonId;
    }

    public Long getBookId() {
        return BookId;
    }

    public void setBookId(Long BookId) {
        this.BookId = BookId;
    }

}
