package matthiasseifert.de.sakuranimangacollection.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SERIES_ASSIGNMENT".
 */
public class SeriesAssignment {

    private Long id;
    private Long SuperiorSeriesId;
    private Long BookId;

    public SeriesAssignment() {
    }

    public SeriesAssignment(Long id) {
        this.id = id;
    }

    public SeriesAssignment(Long id, Long SuperiorSeriesId, Long BookId) {
        this.id = id;
        this.SuperiorSeriesId = SuperiorSeriesId;
        this.BookId = BookId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSuperiorSeriesId() {
        return SuperiorSeriesId;
    }

    public void setSuperiorSeriesId(Long SuperiorSeriesId) {
        this.SuperiorSeriesId = SuperiorSeriesId;
    }

    public Long getBookId() {
        return BookId;
    }

    public void setBookId(Long BookId) {
        this.BookId = BookId;
    }

}
